### ISSUE TITLE
Navigation Client Comments

### ISSUE THREAD

**Issue by carrieverde** [BravelyCreated/sohaveyouheard#1]
Changes to the Navigation based on client comments:
- [ ] Remove Contact Us from top nav, focus should be on contribute
- [ ] The close stacking of the 3 lines (social, nav, and search) is making this corner a bit heavy. Maybe add the search to the first line? Make the search bar smaller, and/or add more space between lines.
- [ ] Deemphasize the social buttons (they're a bit too large and dark), but keep the size of the TUO button.
- [ ] Consider removal of social buttons altogether if no logical place to link to

Additional Feedback from client:

- [ ] Is there a reason that the drop down menu is right justified and bumped over?
- [ ] We have not switched our Twitter icon to "X" yet on all of our other sites and it may be better to wait, especially if X starts charging to use the platform.
- [ ] The top nav (including the social icons) wraps in a weird way in smaller sizes. Can this be adjusted to be more responsive?

**Comment by samgdesign** [comment]
Resolved from push on 10/3
