### ISSUE TITLE
Homepage Edits

### ISSUE THREAD

**Issue by carrieverde** [BravelyCreated/sohaveyouheard#2]
- [ ] The melon color in the background is making the transition into the yellow/lime a bit muddy. Remove the melon color
- [ ] Universal comment for photography: ASHA's photography requirements call for:  "Light/neutral background, high contrast and saturation."
- [ ] Global comment: check all contrast to ensure meeting WCAG (AA) standard
- [ ] The gray footer text seems lighter in color and weight than what exists on https://www.asha.org/ and https://www.thatsunheardof.org/. Can this be adjusted so it's easier to read?

Additional Client Comments:
- [ ] Creative media has provided feedback re: accessibility. They are saying that the site does not meet the Web Content Accessibility Guidelines (WCAG) color contrast standards ASHA uses for its websites. Here are some screen shots (attached)
![image (1)](https://github.com/BravelyCreated/sohaveyouheard/assets/142238679/eb50fd9a-f27c-4995-8e96-5fc448a9d88b)
![image (2)](https://github.com/BravelyCreated/sohaveyouheard/assets/142238679/0e6546ba-7f7b-471c-9377-b90e4fb5e2b5)

**Comment by samgdesign** [comment]
Resolved from push on 10/3
