### ISSUE TITLE
Case Study Page Edits

### ISSUE THREAD

**Issue by carrieverde** [BravelyCreated/sohaveyouheard#3]
- [ ] When content is ready, please make icons the same style and color as the ones on home page.

Additional comments from ASHA Dev:
- [ ] Mobile version – We think that the left column should stack on the top like the company profile page
<img width="162" alt="image" src="https://github.com/BravelyCreated/sohaveyouheard/assets/142238679/f364acf9-35d6-4bcf-a1ee-90f08ff7b01b"> 
<img width="174" alt="image" src="https://github.com/BravelyCreated/sohaveyouheard/assets/142238679/4653544d-d9ce-4e64-aa74-987f665ac29c">

**Comment by samgdesign** [comment]
Resolved from push on 10/3
