### ISSUE TITLE
Code Comments from ASHA Dev Team

### ISSUE THREAD

**Issue by carrieverde** [BravelyCreated/sohaveyouheard#6]
- [ ] Please replace <figcaption> to other tags, eg.<div> Optimizely editor cannot pick it up even though it is specifically added.
- [ ] Can we move page specific classes from <body> to the content section?
<img width="421" alt="image" src="https://github.com/BravelyCreated/sohaveyouheard/assets/142238679/a613dd39-0a88-4bef-af2c-4d02e6784c00">

- [ ] Please remove any page specific CSS class from header. Headers on all pages should have same code including homepage.

**Comment by samgdesign** [comment]
Resolved
